### PR TITLE
Expose custom-impl on docs.rs and add feature-required badges.

### LINKED ISSUE #10: docs.rs should showcase `custom-impl` feature.
Currently the [docs.rs page for critical-section](https://docs.rs/critical-section/latest/critical_section/) does not mention trait `Impl` or macro `custom_impl`, which only appears in public API when a particular feature is set and contains some documentation.
I think docs.rs Cargo metadata should be set to allow docs.rs show all the API. `cfg_attr(..., doc(feature(...))` trick may be additionally used to render "This is supported on crate feature ... only" badges on those APIs.

### PR DESCRIPTION
**Pull request by vi**
Resolves #10.

r? @Dirbaio

### CODE REVIEW

**Comment by Dirbaio** [comment]
Nice! Gating it on `cfg(docsrs)` is to make it build on stable, right?

**Comment by vi** [comment]
> Gating it on cfg(docsrs) is to make it build on stable, right?

Yes. `doc(cfg)` is [unstable](https://doc.rust-lang.org/beta/unstable-book/language-features/doc-cfg.html).

**Comment by vi** [comment]
Note that the change is rather meaningless without a crates.io release.

**Comment by Dirbaio** [comment]
Done! :)

I took the opportunity to expand docs.

**Comment by vi** [comment]
Note: a minor typo:

> WHy not generics?

Upper case '`H`.

**Pull request merged**
